### ISSUE TITLE
Örnek Todo App çalışması

### ISSUE THREAD

**Issue by oytunistrator** [EcoCoding/todo-app#1]
- [ ] Login/Logout Sayfaları - Kullanıcı Girişi
- [ ] Kullanıcının Kategori Ekleyebilmesi
- [ ] Yapılacaklar ekleyebilmesi
- [ ] Yapılacaklara, kategoriler ekleyebilmesi
- [ ] Yapılacak öğenin başka kullanıcılar ile paylaşılması (aynı anda iki kullanıcı aynı maddeyi görebilir)
- [ ] İleriki aşamalarda bunun kendine göre özelleştirilebilmesi (Admin paneli)

![Image](https://github.com/EcoCoding/todo-app/assets/3594944/a32bf68a-acde-40a5-8cb4-de0523fd19a4)

Proje-Repo: [todo-app](https://github.com/EcoCoding/todo-app)

# Öğrenimler:

- [ ] [ReactJS](https://react.dev/learn)
- [ ] HTML/CSS
- [ ] [SASS](https://sass-lang.com/)
- [ ] [NodeJS](https://nodejs.org/docs/latest/api/)
- [ ] Alternatif: Python-Django veya Laravel
- [ ] Bootstrap
